<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Spring Boot Email using FreeMarker</title>
</head>
<body>
	
	<p> <b>ATTENZIONE</b> le credenziali iniziali per l'attivazione del profilo di ${username} scadranno tra ${ore} ore </p>
	<p> Se non hai ancora svolto l'attivazione premi ora sul link qui di seguito </p> 
	<p> ${link} </p> 
	 	
	
</body>
</html>