<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Spring Boot Email using FreeMarker</title>
</head>
<body>

	<p>${utente} ha <b>${azione}</b> richiesta per l'approvazione del <b>${eventType}</b> </p>
	<p>relativo al mese di <b>${mese} ${anno}</b> </p>
</body>
</html>